default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  template: template0


development:
  <<: *default
  database: heart_up_api_development

test:
  <<: *default
  database: heart_up_api_test

production:
  <<: *default
  database: heart_up_api_production
  username: heart_up_api
  password: <%= ENV['heart_up_api_DATABASE_PASSWORD'] %>